module.exports = {
   name: 'en', 
   onlyGroup: '[🤦🏼‍♀️] My commands are only available in groups!\n[-📲-] Contact my developer: https://wa.me/557599400589',
   commandErr: '[🤷🏼‍♀️ ] Oops! An error occurred while executing the command... ',
   noPermBot: '[🚫] I need to be a administrator to execute that!',
   noPermUser: '[🚫] You need to be a administrator to use that!',
   noPermDev: '[🚫] You need to be a developer to use that!',
   langChanged: '[🇺🇸] The language has been changed to English.',
   invArgs: (args) => `You didn\'t provide valid arguments!\nCorrect usage: *${args[0] + args[1]} ${args[2]}*`,
   prefixChanged: (args) => `[💛] The prefix has been changed to: *${args}*`,
   prefixRange: '[🤦🏼‍♀️] The prefix must be a max of 4 characters',
   helpFooter: (prefix) => `*${prefix}help command* to more info\n[example] *${prefix}help lock*`, 
   commandInfo: (prefix, args) => `\`\`\`[${args[0].toUpperCase()}]\`\`\`\n\n${args[4]}\n\n*✦─•─『•💮•』─•─✦*\nCorrect Usage: *${prefix + args[0]} ${args[1]}*\nExample: *${prefix + args[0]} ${args[2]}*\nAliases: *${args[3].join(', ')}*\n*✦─•─『•💮•』─•─✦*`, 
   notFound: '[🤷🏼‍♀️] Command not found!', 
   invalidQuoted: '[🚫] Invalid media type!', 
   invalidUrl: '[🚫] Invalid URL', 
   mentionMedia: '[🤦🏼‍♀️] You need to mention the desired media.', 
   mediaRange: '[🚫] This media is too large to convert.', 
   lyricsNotFd: '[🤷🏼‍♀️] I couldn\'t find that song\'s lyrics.',
   invUser: 'I can\'t found this member, verify if that is a valid number!', 
   alreadyAdm: '[🤦🏼‍♀️] This member is already a admin.', 
   sucessPromote: (mention) => `[✅] The user ${mention} now is an admin!`, 
   sucessDemote: (mention) => `[✅] The user ${mention} was demoted!`, 
   sucessChanges: '[✅] Changes made successfully!', 
   isNotAdm: '[🤦🏼‍♀️] This member is not a admin.', 
   remaining: ([hour, min, sec]) => `Wait for cooldown ends...\n*[⏳] ${`${hour > 0 ? hour + ' hours' : ''} ${min > 0 ? min + ' minutes' : ''} ${sec > 0 ? sec + ' seconds' : ''}`.trim()} remaining...*`, 
   banAdmErr: '[🤦🏼‍♀️] I can\'t remove a admin!', 
   pingMsg: ['🏓 º° Calculating...', '*🌐 °º Response time: {ping} ms*'], 
   mentionMe: (prefix) => `💛 My prefix in this group is *${prefix}*\n°º Type ${prefix}help to see the list of commands!`, 
   levelUp: (level, name) => `🎊 *Congratulations!*\n*You've risen to the level: ${level} [${name}]*`, 
   profileStats: ({ xp, level, nextLevel, money }) => `*[🎖️] Profile Stats [🎖️]*\n\n*{⚗️} Xp:* \`\`\`${xp}\`\`\`\n*{🥋} Level:* \`\`\`${level}\`\`\`\n*{🎴} Next Level:* \`\`\`${nextLevel}\`\`\`\n*{💰} Money:* \`\`\`${money}\`\`\`\n\n${new Date().toLocaleString('en-us', {timeZone: 'America/Sao_Paulo', dateStyle: 'medium', timeStyle: 'short' }) }`,
   invBackgroundColor: (arrayColors, levelReqArray) => `I did\'nt find this color, check the list:\n\n${arrayColors.map(i => `➜ *${levelReqArray.includes(i) ?  i + ' (Lvl 2+)' : i }*`).join('\n')}`, 
   insufficientLvl: (levelReq) => `[🤷🏼‍♀️] Your level is too low for that...\n*Level required:* ${levelReq}`, 
   loading: '[⏳] Loading...', 
   rangeYtVideo: 'This video exceeds the required minute limit!\n*Max: 10 minutes*', 
   willBeSent: (seconds) => `*The question will be sent in ${seconds} seconds...*`, 
   questAnagram: (shuffledName, hint, time) => `❲📖° ANAGRAM °📖❳\n\n➜ \`\`\`Word: ${shuffledName} \`\`\`\n➜ \`\`\`Hint: ${hint} \`\`\`\n\n❲⏰❳ *${time} seconds*`, 
   correctAnswer: (reward) => `🎊 *Congratulations, you got it!*\n[💰] reward: \`\`\`+${reward}\`\`\``, 
   welcomeMsg: (member) => `💛 Welcome @${member}, I hope you have fun here on the group!`, 
   removedMsg: (member) => `🤷🏼‍♀️ The member @${member} left the group!`, 
   blacklist: '🤦🏼‍♀️ You can\'t use the commands because you\'re already blacklisted'

};
